#!/bin/bash
DOCKER_TAG="$1"
VERSION_TAG="$2"
BASEDIR=$(dirname "$0")
if [ -z "$DOCKER_TAG" ]
then
    echo "Docker Image Tag missing."
    exit 1
fi

echo "CAUTION: This build won't succeed if this repository is a submodule of another repository!"
if [ -z $VERSION_TAG ]
then 
    docker build -f "$BASEDIR"/../docker/Dockerfile-develop -t "$DOCKER_TAG":latest "$BASEDIR"/../.
else
    docker build -f "$BASEDIR"/../docker/Dockerfile-develop -t "$DOCKER_TAG":latest -t "$DOCKER_TAG":"$VERSION_TAG" "$BASEDIR"/../.
fi
echo "CAUTION: This build won't succeed if this repository is a submodule of another repository!"


#--cache-from "$DOCKER_TAG":latest