rp:
  amqp:
    host: localhost
    user:
    pass:
    apiuser:
    apipass:
  db:
    user:
    pass:
    host: localhost
  plugins:
    rootDir: /Users/pavel_bortnik/ReportPortal5/data/storage/
  datasource:
    maximumPoolSize: 12
  binarystore:
#    path: /Users/pavel_bortnik/ReportPortal5/data/storage
    type: minio
    minio:
      endpoint: http://localhost:9000
      accessKey:
      secretKey: