rp:
  amqp:
    host: localhost
  db:
    host: localhost
  plugins:
    rootDir: /Users/pavel_bortnik/ReportPortal5/data/storage/
  datasource:
    maximumPoolSize: 12
  binarystore:
#    path: /Users/pavel_bortnik/ReportPortal5/data/storage
    type: minio
    minio:
      endpoint: http://localhost:9000
      accessKey: minio
      secretKey: minio123

#logging:
##  name:
##    file: ${java.io.tmpdir}${file.separator}reportportal${file.separator}logs${file.separator}${spring.application.name}.log
#  level:
#    org:
#      hibernate:
#        SQL: info